apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.type }}
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
